Repository ESGI-te/challenge-week-symfony, pull requests merged in 2023-02, with the labels that each got.

#1 ✨ Add user authentication
  .env
  .gitignore
  composer.json
  composer.lock
  config/bundles.php
  config/packages/doctrine.yaml
  config/packages/ramsey_uuid_doctrine.yaml
  config/packages/security.yaml
  config/packages/sensio_framework_extra.yaml
  config/packages/uid.yaml
  src/Controller/DefaultController.php
  src/Controller/SecurityController.php
  src/Entity/User.php
  src/Form/RegisterType.php
  src/Repository/UserRepository.php
  src/Security/Authenticator.php
  src/Service/MailService.php
  src/Service/RegisterService.php
  symfony.lock
  templates/default/index.html.twig
  templates/emails/accountVerification.html.twig
  templates/security/login.html.twig
  templates/security/register.html.twig
Labels: ✨ feature

#2 ✨ Add entities
  src/Entity/Comment.php
  src/Entity/Favorite.php
  src/Entity/Listening.php
  src/Entity/Litigation.php
  src/Entity/LitigationObject.php
  src/Entity/ModeratorRequest.php
  src/Entity/Music.php
  src/Entity/Playlist.php
  src/Entity/Role.php
  src/Entity/User.php
  src/Repository/CommentRepository.php
  src/Repository/FavoriteRepository.php
  src/Repository/ListeningRepository.php
  src/Repository/LitigationObjectRepository.php
  src/Repository/LitigationRepository.php
  src/Repository/ModeratorRequestRepository.php
  src/Repository/MusicRepository.php
  src/Repository/PlaylistRepository.php
  src/Repository/RoleRepository.php
Labels: ✨ feature

#3 ✨ Add username to User
  src/Entity/User.php
  src/Form/RegisterType.php
Labels: ✨ feature

#7 🚑️ Turn constants into class
  src/Entity/User.php
  src/Service/RegisterService.php
  src/Utilities/Constants.php
  src/constants.php
Labels: 🚑️ hotfix

#9 ✨ Add music upload
  .gitignore
  Dockerfile
  composer.json
  composer.lock
  config/services.yaml
  src/Controller/MusicController.php
  src/Entity/Music.php
  src/Form/UploadMusicType.php
  src/Service/MailService.php
  src/Service/MusicService.php
  src/Service/RegisterService.php
  src/Utilities/Constants.php
  templates/default/index.html.twig
  templates/music/upload.html.twig
Labels: ✨ feature

#10 🔧 Update .gitignore
  .gitignore
Labels: 🔧 chore
